name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Render user data with image tag
        run: |
          sed "s/__IMAGE_TAG__/${IMAGE_TAG}/g" user-data.sh > rendered-user-data.sh

      - name: Create new launch template version
        run: |
          aws ec2 create-launch-template-version \
            --launch-template-name devops-lt-20260217183402239600000001 \
            --source-version '$Latest' \
            --launch-template-data "UserData=$(base64 -w 0 rendered-user-data.sh)"

      - name: Update ASG to use latest launch template version
        run: |
          aws autoscaling update-auto-scaling-group \
            --auto-scaling-group-name terraform-20260217183408750400000003 \
            --launch-template LaunchTemplateName=devops-lt-20260217183402239600000001,Version='$Latest'

      - name: Start rolling instance refresh
        run: |
          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name terraform-20260217183408750400000003
